comp500/quilt-serverside-mods

- README.md
[add better op](https://github.com/The-Tiny-Taters/Better-Op)
> add better op

- README.md
Adds [HealthCare](https://github.com/samolego/HealthCare) mod, which adds server-side healthbars.
I put it under utility, as I think that's the most appropriate category.
> Add healthcare mod

- README.md
Lapis Warps, GVault, and GShop.
> Add a few more of my mods

- README.md
Supports a forked version of lithium by the same mod author that has a better entity handling engine.
> Added hopperOptimizations

- README.md
Expanded Axe Enchanting
Expanded Armor Enchanting
Expanded Weapon Enchanting
Expanded Trident Enchanting
Infinity Fix
Carpet Without /player
Neutral Animals
Neutral Mobs
No Teleport Cooldown
Eternal Eats
Grind Enchantments
ParadoxSlabs
Powershot
Better Beacon
Spice of Fabric
The Toast Mod
Good Ol' Regen
Extension
You can't damage me!
Craftable Enchanted Golden Apple
Rotten Flesh to Feather
Glowing Potion
Fabric Death Messages
Server Tick
SimpleChat - Chat mod for Fabric servers
Head Index
BineClaims
FabricExporter
Scarpet Os Utils
Datapack Easy
Anti X-ray
BlockBot
Discord Integration (Mod)
Struct Plus
SmoothBedrock By Blayyke
Swamp Oak Redux
Ore-Readout
Volatile Entity Cramming
Bedrock Breaking
Memento Mori
BetterLeads
> Added all missing mods from modrinth except libraries

- README.md
Added in "Commands/Chat"
See it here: [John-Paul-R/Essential-Commands](https://github.com/John-Paul-R/Essential-Commands)
> Add Essential Commands mod.

- README.md
Marked as draft until mod page is completed and approved.
> Add Semblance

- README.md
https://github.com/StoneLabs/delayed-respawn
see readme for details. 
Though, I'll do some more polishing on this mod and its readme with the first snapshots before the 1.18 release. At the moment it's still a little rough around the edges. Works without problems though.
Thanks,
Stone
> Add delayed respawn

- README.md
https://github.com/StoneLabs/golemf/
see readme for details.
Thanks,
Stone
> Add GolemF

- README.md
https://github.com/StoneLabs/strains-of-ascension
see readme for details.
Thanks,
Stone
> Add Strains of Ascension

- README.md
Added the Progression and Spawnbook mods
Full disclosure: I made/helped make these mods, so if that is not allowed, my apologies.
I wasn't sure where to put Progression between Game Mechanics Tweaks or Server Management. I decided on Server Management.
Spawnbook was placed under Join Messages/MOTD.
> added progression and spawnbook

- README.md
Added working graves under Graves/Death.
See readme for details:
https://github.com/StoneLabs/working-graves
Thanks,
Stone
> Add Working Graves

- README.md
Add mod that adds hat command for 1.17
https://github.com/AquUpd/hat-command
> Hat command mod

- README.md
The author of Slapmap said he will no longer be able to maintain the mod and has given me (and anyone, really) permission to maintain it. I've updated the link accordingly to the new proper repository
Here's the source of the information https://github.com/kalkronline/slapmap/pull/3
> updated the URL of Slapmap

- README.md
> Mark SmoothBedrock as unsupported 

- README.md
As of BedrockWaters [v1.5.0](https://www.curseforge.com/minecraft/mc-mods/bedrockwaters/files/3466383), the mod is client-side, and it does nothing on the server.
> Remove BedrockWaters

- README.md
> Add IceBoatF

- README.md
The link to Infinity Water Bucket shows up twice in the list, this pull request removes the duplicate entry.
> 🔥 Removed duplicate "Infinity Water Bucket" entry

- README.md
https://github.com/ChloeDawn/mc7569-fix
> Append MC-7569 Fix to Bugfixes

- README.md
Imagine not having carpet-fixes in a list of mods that fix bugs...
> Added Carpet-Fixes

- README.md
This PR adds my Discord <=> Minecraft bridge mod.
> Add QChatLink

- README.md
See https://modrinth.com/mod/blacksmiths
> Add Blacksmiths (Taterzens addon)

- README.md
Use the updated OptiFine alternatives list
> Update OptiFine alternatives

- README.md
Adds Enforce Gamemode (https://modrinth.com/mod/enforce-gamemode) to the Server Management category
> Add Enforce Gamemode

- README.md
Here's another one for your list.  Thanks!
> Add MobFilter to serverside mod list

- README.md
Basically like appleskin but serverside :)
> Add `lakotnik - hunger preview` mod

- README.md
> add Copper Hopper

- README.md
https://github.com/Giggitybyte/SleepWarp
> Add SleepWarp

- README.md
https://github.com/Giggitybyte/Aliases
> Add Aliases

- README.md
For Simple Quests havent found a fitting category so i created a new one if thats ok
> Add Improved Mobs and Simple Quests

- README.md
Also, since issues are disabled on this repository, I'd love if CF links were replaced with GitHub links when possible. Modrinth links are fine.
> Fix duplicated YouCantDamageMe

- README.md
- src/mods/hydrogen.toml
See https://github.com/CaffeineMC/hydrogen-fabric/commit/95da36046c2f55617a76ebb8ea1e1f2a330330e5.
> Mark Hydrogen as abandoned

- src/mods/skylands.toml
Idk what happened to previous pr
> Add skylands

- src/mods/filledtothebrim.toml
Add curseforge and github links for FilledtoThebrim
> add more data for the mod FilledToTheBrim (GH,CF)

- src/mods/better-fabric-console.toml
Adds Better Fabric Console https://www.curseforge.com/minecraft/mc-mods/better-fabric-console
> Add Better Fabric Console

- src/mods/antilogout.toml
adds AntiLogout mod, https://modrinth.com/mod/noexits
(makes player's body still be online when disconnecting during combat)
> Add antilogout mod

- src/mods/dory.toml
> Added the 'Dory' mod.

- src/mods/squaremap.toml
Added new lightweight web map.
> Added new map plugin(squaremap)

- src/mods/maintenance-mode.toml
- src/mods/sdlink.toml
added sdlink and maintenance mode
> Add Simple discord link & Maintenance mode
